apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./was-hello-world-umbrella-chart-1
- ./was-hello-world-umbrella-chart-2
- ./was-hello-world-multiple-sources-1
- ./was-hello-world-multiple-sources-2
- ./was-hello-world-multiple-sources-cm-1
- ./was-hello-world-multiple-sources-cm-2
- ./event-streams-starter-app

commonLabels:
  managed-by: argoCD-jesus