apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ../../../apps/sample-app/overlays/staging
# - ../../../apps/websphereliberty-app-sample/overlays/staging

patches:
  - path: add-license.patch.yaml
    target:
      labelSelector: "liberty=true"