apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -umbrella

resources:
- ./argoApp.yaml
- ./configmap.yaml

# patches:
# - path: patch.yaml
#   target:
#     kind: ConfigMap
#   options:
#     allowNameChange: true