apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: "-1"

resources:
- ./argoApp.yaml
- ./configmap.yaml

commonLabels:
  managed-by: argoCD-jesus

# patches:
# - path: patch.yaml
#   target:
#     kind: ConfigMap
#   options:
#     allowNameChange: true