apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
 - target:
      group: liberty.websphere.ibm.com
      version: v1
      kind: WebSphereLibertyApplication
      name: websphereliberty-app-sample
   path: wsla.patch.yaml

namespace: staging