# Internal plain listener
# =======================
# security.protocol=PLAINTEXT
# bootstrap.servers=es-default-kafka-bootstrap.dev.svc\:9092

# Topic
# =====
# topic=dev-es-starter-app

###################################################################
## Consumer specific properties
###################################################################
# group.id=dev-es-starter-app
# client.id=dev-es-starter-app
# auto.offset.reset=earliest
# enable.auto.commit=false
# key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
# value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

###################################################################
## Producer specific properties
###################################################################
# acks=1
# key.serializer=org.apache.kafka.common.serialization.StringSerializer
# value.serializer=org.apache.kafka.common.serialization.StringSerializer

apiVersion: v1
kind: Secret
metadata:
  name: starter-app-kafka-properties
data:
  kafka.properties: IyBJbnRlcm5hbCBwbGFpbiBsaXN0ZW5lcgojID09PT09PT09PT09PT09PT09PT09PT09CnNlY3VyaXR5LnByb3RvY29sPVBMQUlOVEVYVApib290c3RyYXAuc2VydmVycz1lcy1kZWZhdWx0LWthZmthLWJvb3RzdHJhcC5kZXYuc3ZjXDo5MDkyCgojIFRvcGljCiMgPT09PT0KdG9waWM9ZGV2LWVzLXN0YXJ0ZXItYXBwCgojIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjCiMjIENvbnN1bWVyIHNwZWNpZmljIHByb3BlcnRpZXMKIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIwpncm91cC5pZD1kZXYtZXMtc3RhcnRlci1hcHAKY2xpZW50LmlkPWRldi1lcy1zdGFydGVyLWFwcAphdXRvLm9mZnNldC5yZXNldD1lYXJsaWVzdAplbmFibGUuYXV0by5jb21taXQ9ZmFsc2UKa2V5LmRlc2VyaWFsaXplcj1vcmcuYXBhY2hlLmthZmthLmNvbW1vbi5zZXJpYWxpemF0aW9uLlN0cmluZ0Rlc2VyaWFsaXplcgp2YWx1ZS5kZXNlcmlhbGl6ZXI9b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VyaWFsaXphdGlvbi5TdHJpbmdEZXNlcmlhbGl6ZXIKCiMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMKIyMgUHJvZHVjZXIgc3BlY2lmaWMgcHJvcGVydGllcwojIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjCmFja3M9MQprZXkuc2VyaWFsaXplcj1vcmcuYXBhY2hlLmthZmthLmNvbW1vbi5zZXJpYWxpemF0aW9uLlN0cmluZ1NlcmlhbGl6ZXIKdmFsdWUuc2VyaWFsaXplcj1vcmcuYXBhY2hlLmthZmthLmNvbW1vbi5zZXJpYWxpemF0aW9uLlN0cmluZ1NlcmlhbGl6ZXI=