global: {}
was-liberty-hello-world:
  lastConfigLoaded: valueFromConfigManagerYAML-test
  appName: was-liberty-hello-world-helm-umbrella-chart
  annotations:
    annotationcm1: "An annotation from ConfigManager yaml file"
    annotationcm2: "An annotation from ConfigManager yaml file"
    annotationcm3: "An annotation from ConfigManager yaml file"
