apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: was-liberty-hello-world-umbrella-chart
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: applications
  source:
    repoURL: https://github.com/giss-gitops/multi-tenancy-gitops-apps.git
    path: GISS/dev/was-hello-world-umbrella-chart
    targetRevision: master
    helm:
      valueFiles:
        - values/configManager.yaml
        - values/PyS.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true