apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-helm-example
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    chart: hello-world
    repoURL: https://helm.github.io/examples
    targetRevision: 0.1.0
    helm:
      releaseName: hello-world-helm
      values: |
        image:
          repository: icr.io/appcafe/open-liberty/samples/getting-started
          tag: latest
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true